package org.ojas.data;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuditMessageData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "AUDITMESSAGEDATA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "AUDITMESSAGEDATA_ID_SEQ", name = "AUDITMESSAGEDATA_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String auditMessage;

	private java.lang.String auditRef;

	public AuditMessageData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getAuditMessage() {
		return this.auditMessage;
	}

	public void setAuditMessage(java.lang.String auditMessage) {
		this.auditMessage = auditMessage;
	}

	public java.lang.String getAuditRef() {
		return this.auditRef;
	}

	public void setAuditRef(java.lang.String auditRef) {
		this.auditRef = auditRef;
	}

	public AuditMessageData(java.lang.Long id, java.lang.String auditMessage,
			java.lang.String auditRef) {
		this.id = id;
		this.auditMessage = auditMessage;
		this.auditRef = auditRef;
	}

}