package org.ojas.data;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ProcessData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROCESSDATA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PROCESSDATA_ID_SEQ", name = "PROCESSDATA_ID_GENERATOR")
	private java.lang.Long id;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private org.ojas.data.SmsMessageData smsMessageData;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private org.ojas.data.AuditMessageData auditMessageData;

	private java.lang.Integer smsResult;

	private java.lang.Integer auditResult;

	public ProcessData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public org.ojas.data.SmsMessageData getSmsMessageData() {
		return this.smsMessageData;
	}

	public void setSmsMessageData(org.ojas.data.SmsMessageData smsMessageData) {
		this.smsMessageData = smsMessageData;
	}

	public org.ojas.data.AuditMessageData getAuditMessageData() {
		return this.auditMessageData;
	}

	public void setAuditMessageData(
			org.ojas.data.AuditMessageData auditMessageData) {
		this.auditMessageData = auditMessageData;
	}

	public java.lang.Integer getSmsResult() {
		return this.smsResult;
	}

	public void setSmsResult(java.lang.Integer smsResult) {
		this.smsResult = smsResult;
	}

	public java.lang.Integer getAuditResult() {
		return this.auditResult;
	}

	public void setAuditResult(java.lang.Integer auditResult) {
		this.auditResult = auditResult;
	}

	public ProcessData(java.lang.Long id,
			org.ojas.data.SmsMessageData smsMessageData,
			org.ojas.data.AuditMessageData auditMessageData,
			java.lang.Integer smsResult, java.lang.Integer auditResult) {
		this.id = id;
		this.smsMessageData = smsMessageData;
		this.auditMessageData = auditMessageData;
		this.smsResult = smsResult;
		this.auditResult = auditResult;
	}

}